### ISSUE TITLE
pre-populate ICES rectangle

### ISSUE THREAD

**Issue by pgmccann** [StAResComp/sifids#15]
As a fisherman I would like the app to automatically pre-populate ICES rectangle (in the FISH-1 form) https://github.com/StAResComp/sifids/issues/5, https://github.com/StAResComp/sifids/issues/6, https://github.com/StAResComp/sifids/issues/7, https://github.com/StAResComp/sifids/issues/8

**Comment by Kylaorr** [comment]
Must - with a dropdown menue option if fishing occurs in more than one rectangle
