### ISSUE TITLE
field for number of lobsters per date

### ISSUE THREAD

**Issue by pgmccann** [StAResComp/sifids#18]
As a fisherman I would like to have an additional field for number of lobsters per date as this would help me remember how many I caught on a particular day and help me fill out the weight of the catch (which is a required field in the fish 2 form) https://github.com/StAResComp/sifids/issues/5

**Comment by Kylaorr** [comment]
Should - could include this as an 'optional' field after weight. Number of animals difficult to obtain for prawns and crabs, but could possibly estimate if fisherman wanted to.
