### ISSUE TITLE
app is showing defacto icon, and Home name

### ISSUE THREAD

**Issue by bsdtec** [StAResComp/sifids#228]
**Describe the bug**
installed sifids app is showing defacto icon, and Home name in app draw on android phones

**To Reproduce**
1. Install App
2. Open App draw
3. Scroll down
4. See error -- App named Home and defacto Android Icon

**Expected behavior**
Properly named App with appropriate Icon

**Smartphone (please complete the following information):**
 - Device: InFocus M512
 - Android version: 4.4.2
 - App version 1.0-dev  (0.6.5)

**Additional context**
Have forked branched and fixed the issue, pull request pending.

**Comment by pgmccann** [comment]
Thanks for the PR! App name and Icons have been amended.
