### ISSUE TITLE
build breaks with newer gradle

### ISSUE THREAD

**Issue by bsdtec** [StAResComp/sifids#231]
**Describe the bug**
android studio wants to upgrade gradle plugin to version 3.2.1 and gradle to version 4.6, after doing this build breaks and complaining about invalid id's in the build values.xml file.

**To Reproduce**
1. update gradle as per android studio recommendation
2. wait for gradle and plugin to install and configure
3. android studio will automatically try and rebuild, build fails

**Expected behavior**
compiling to complete without error and apk produced

**Additional context**
Work around at the moment is to set gradle to 3.1.4 in gradle config.

classpath 'com.android.tools.build.gradle:3.1.4'

**Comment by pgmccann** [comment]
Have updated the config - now builds using gradle plugin 3.3.1 and gradle 4.10.1
