### ISSUE TITLE
pre-populate ICES rectangle (in the EU Logbook)

### ISSUE THREAD

**Issue by pgmccann** [StAResComp/sifids#35]
As a fisherman I would like the app to automatically pre-populate ICES rectangle (in the EU Logbook) https://github.com/StAResComp/sifids/issues/6

**Comment by Kylaorr** [comment]
Must - with dropdown menue option if fishing in more than one ICES square

**Comment by pgmccann** [comment]
EU Logbook is out of scope for the current project.
