### ISSUE TITLE
pre-populate species with seasonal changes

### ISSUE THREAD

**Issue by pgmccann** [StAResComp/sifids#47]
As a fisherman I would like the app to automatically pre-populate species with seasonal changes (in the FISH-1 form) https://github.com/StAResComp/sifids/issues/6, https://github.com/StAResComp/sifids/issues/8

**Comment by Kylaorr** [comment]
Should - as long as more than one species can be pre-populated, e.g. some fishermen may fish crab and lobster on the same day.

**Comment by pgmccann** [comment]
This won't be included as part of this project - species list is static, though user can select favourites, which can be edited subsequently.
