### ISSUE TITLE
pre-populate buyer

### ISSUE THREAD

**Issue by pgmccann** [StAResComp/sifids#49]
As a fisherman I would like the app to automatically pre-populate buyer (in the FISH-1 form) https://github.com/StAResComp/sifids/issues/6, https://github.com/StAResComp/sifids/issues/8

**Comment by Kylaorr** [comment]
Must

**Comment by pgmccann** [comment]
Could add this to preferences quite easily.

**Comment by pgmccann** [comment]
Done in https://github.com/StAResComp/sifids/commit/4bf4339873c8a15f3c77c188e11a119214c7aa1c
