### ISSUE TITLE
summary plots of my landings (kg and value) per month and a summary for the year

### ISSUE THREAD

**Issue by pgmccann** [StAResComp/sifids#61]
As a fisherman, the types of 'outputs' that would be useful include summary plots of my landings (kg and value) per month and a summary for the year, so that I can quickly see which was the 'biggest month' in terms of landings.https://github.com/StAResComp/sifids/issues/6, https://github.com/StAResComp/sifids/issues/7

**Comment by Kylaorr** [comment]
Should
