### ISSUE TITLE
enter my landings weight (kg) now or later

### ISSUE THREAD

**Issue by pgmccann** [StAResComp/sifids#73]
As a fisherman I would like the app to allow me to  "enter my landings weight (kg) now or later". If 'later' is selected then the fisherman can go back to an 'incomplete form' and enter all weights once they receive their landings tally from the buyer (*see note below). https://github.com/StAResComp/sifids/issues/8

**Comment by Kylaorr** [comment]
Must - maority of fishermen wont be able to enter weights on the day they went fishing

**Comment by pgmccann** [comment]
App works with the weekly FISH1 Form paradigm - users can go back and edit at any point.
