### ISSUE TITLE
Buyer (JPL) Comment #3

### ISSUE THREAD

**Issue by Ali-McKnight** [StAResComp/sifids#87]
As a buyer, we weigh landings (gross) at the unit before being catch is graded and take net weight after discards, etc. and this is given back to fishermen generally electronically (as excel or pdf) but some prefer as paper copy.  Fishermen also give us their expected landing weights, which is a valuable part of the process.  If fishermen were able to send their estimates via the app to us as they are coming back to harbour, it would be useful and also if recorded electronically this woudl be a useful comparison to final weights.   So in sumamry, if the app could also communicate between fishermen and buyer we would find this helpful and we could forward weights direct to the app.

Other info useful would be ICES square as if this has not been recorded by the fishermen it can be time consuming to look up/enter as we have to look up AIS tracks.  .

**Comment by pgmccann** [comment]
ICES square isn't currently available on a daily basis; won't have any mechanism for communicating with buyer in this project.
